[base]
apt = [
    "build-essential",
    "npm",
    "python-is-python3",
    "python3-pip",
    "wslu",
]
winget = [
    "7zip.7zip",
    "Docker.DockerDesktop",
    "Git.Git",
    "JetBrains.IntelliJIDEA.Community.EAP",
    "Microsoft.VisualStudioCode",
    "Starship.Starship",
]

[work]
winget = [
    "WiresharkFoundation.Wireshark"
]
