[base]
apt = [
    "npm",
    "wslu",
]
winget = [
    "7zip.7zip",
    "BurntSushi.ripgrep.MSVC",
    "cURL.cURL",
    "Git.Git",
    "Microsoft.VisualStudioCode",
    "Postman.Postman",
    "python3",
    "Spotify.Spotify",
    "Starship.Starship",
]

[personal]
pip = [
    "python-dotenv",
    "Telethon",
    "tzdata",
]
winget = [
    "AgileBits.1Password",
    "AgileBits.1Password.CLI",
    "Discord.Discord",
    "EpicGames.EpicGamesLauncher",
    "Google.Chrome",
    "Mozilla.Firefox",
    "PortSwigger.BurpSuite.Community",
    "RevoUninstaller.RevoUninstaller",
    "Telegram.TelegramDesktop",
    "Valve.Steam",
    "VideoLAN.VLC",
    # Lenovo Legion 5 Pro
    "-ARP\\Machine\\X86\\Legion Arena_is1",
    "-ARP\\Machine\\X86\\Lenovo Now",
]

[work]
winget = [
    "Bitwarden.Bitwarden",
    "Docker.DockerDesktop",
    "Insecure.Nmap",
    "JetBrains.IntelliJIDEA.Community.EAP",
    "Microsoft.Teams",
    "Microsoft.WindowsSDK", # for cffi <- cryptography <- scapy, or Microsoft.VisualStudio.2022.BuildTools w/SDK + C++ build tools
    "PortSwigger.BurpSuite.Professional",
    "SlackTechnologies.Slack",
    "tailscale.tailscale",
    "WinSCP.WinSCP",
    "WiresharkFoundation.Wireshark",
]
