[base]
apt = [
    "build-essential",
    "fish", # TODO: sudo apt-add-repository ppa:fish-shell/release-3, or choose brew fish instead
    "npm",
    "python-is-python3",
    "python3-pip",
    "wslu",
]
brew = [
    "starship"
]
pip = [
    "pipdeptree",
    "wheel",
]
winget = [
    "7zip.7zip",
    "Docker.DockerDesktop",
    "Git.Git",
    "JetBrains.IntelliJIDEA.Community.EAP",
    "Microsoft.VisualStudioCode",
    "Starship.Starship",
]

[work]
pip = [
    "semgrep"
]
