[base]
apt = [
    "build-essential",
    "npm",
    "python-is-python3",
    "python3-pip",
    "python3-venv",
    "wslu",
]
winget = [
    "-Microsoft.DevHome",
    "7zip.7zip",
    "cURL.cURL",
    "Git.Git",
    "Microsoft.VisualStudioCode",
    "Postman.Postman",
    "python3",
    "Spotify.Spotify",
    "Starship.Starship",
]

[personal]
winget = [
    "AgileBits.1Password",
    "Discord.Discord",
    "EpicGames.EpicGamesLauncher",
    "Google.Chrome",
    "RevoUninstaller.RevoUninstaller",
    "Telegram.TelegramDesktop",
    "Valve.Steam"
]

[work]
winget = [
    "Bitwarden.Bitwarden",
    "Docker.DockerDesktop",
    "Insecure.Nmap",
    "JetBrains.IntelliJIDEA.Community.EAP",
    "Microsoft.Teams",
    "Microsoft.WindowsSDK", # for cffi <- cryptography <- scapy, or Microsoft.VisualStudio.2022.BuildTools w/SDK + C++ build tools
    "PortSwigger.BurpSuite.Professional",
    "SlackTechnologies.Slack",
    "tailscale.tailscale",
    "WinSCP.WinSCP",
    "WiresharkFoundation.Wireshark",
]
