[base]
apt =[
    "build-essential",
    "keychain",
]
brew = [
    "fish",
    "jq",
    "starship",
]
pip = [
    "wheel",
    "pipdeptree",
    "pipx",
    "pyperclip",
]

[pentest]
brew = [
    "gitleaks",
    "sccache",
    "slowhttptest",
    "trufflehog",
]
fisher = [
    "jorgebucaran/nvm.fish",
]
pipx = [
    "objection",
    "semgrep",
]

[rust]
cargo = [
    "cargo-expand",
    "cargo-update",
    "sccache",
]
