[base]
brew = [
    "fish",
    "jq",
    "starship",
]

[work]
brew = [
    "apktool",
]
fisher = [
    "jorgebucaran/nvm.fish",
]
pip = [
    "wheel",
    "frida-tools",
    "objection",
    "pipdeptree",
    "semgrep",
    "scapy[complete]",
]

[rust]
cargo = [
    "cargo-expand",
    "cargo-update",
    "sccache",
]
