[base]
apt =[
    "build-essential",
    "python-is-python3",
    # Python build
    "libbz2-dev",
    "libffi-dev",
    "liblzma-dev",
    "libncursesw5-dev",
    "libreadline-dev",
    "libsqlite3-dev",
    "libssl-dev",
    "libxml2-dev",
    "libxmlsec1-dev",
    "tk-dev",
    "xz-utils",
    "zlib1g-dev",
]
brew = [
    "fish",
    "jq",
    "pyenv",
    "starship",
]

[work]
brew = [
    "gitleaks",
    "sccache",
    "slowhttptest",
    "trufflehog",
]
fisher = [
    "jorgebucaran/nvm.fish",
]
pip = [
    "wheel",
    "pipdeptree",
]
pipx = [
    "objection",
    "scapy[complete]",
    "semgrep",
]

[rust]
cargo = [
    "cargo-expand",
    "cargo-update",
    "sccache",
]
