[env_var.PROXY]
variable = "HTTPS_PROXY"
format = '[\(proxy on\)](purple) '

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "=${count}"
deleted = "✘${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
renamed = "»${count}"
staged = "+[${count}](green)"
stashed = "$${count}"
untracked = "?${count}"

[python]
python_binary = ["python3", "python", "python2"]
