["Apple Global Domain"]
AppleICUForce24HourTime = true
AppleScrollerPagingBehavior = true # Jump to spot clicked in scroll bar
AppleShowAllExtensions = true
NSAutomaticCapitalizationEnabled = false
NSAutomaticPeriodSubstitutionEnabled = false # No more double space for period
NSAutomaticQuoteSubstitutionEnabled = false
NSAutomaticSpellingCorrectionEnabled = false
NSNavPanelExpandedStateForSaveMode = true # Expand save dialog by default
PMPrintingExpandedStateForPrint = true # Expand the print dialog by default

["com.apple.AppStore"]
InAppReviewEnabled = false

["/Library/Preferences/com.apple.commerce"]
AutoUpdate = true

["com.apple.dock"] # killall Dock
enable-spring-load-actions-on-all-items = true # Drag file over Dock item to open the app
expose-group-apps = false
mineffect = "suck"
minimize-to-application = true
mru-spaces = false # Don't rearrange Spaces based on use
show-recents = false

["com.apple.finder"] # killall Finder
_FXSortFoldersFirst = true
AppleShowAllFiles = true
FXArrangeGroupViewBy = "Name"
FXDefaultSearchScope = "SCcf" # Default search scope to current folder
FXEnableExtensionChangeWarning = false
FXPreferredViewStyle = "Nlsv" # Prefer list view
NSDocumentSaveNewDocumentsToCloud = false
ShowPathbar = true # Show breadcrumbs at the bottom

["com.apple.menuextra.clock"] # killall SystemUIServer
DateFormat = "\"EEE d MMM H:mm\""
FlashDateSeparators = true

["com.apple.screensaver"]
askForPassword = true # Ask for password after sleep/screen saver

["/Library/Preferences/com.apple.SoftwareUpdate"]
AutomaticCheckEnabled = true
AutomaticDownload = true
AutomaticallyInstallMacOSUpdates = true
ConfigDataInstall = true
CriticalUpdateInstall = true

["com.100hps.captin"]
auto_launch = true
show_dock_icon = false
show_menu_bar_icon = false
show_on_launch = false
SUAutomaticallyUpdate = true

["com.sempliva.Tiles"]
LaunchAtLoginEnabled = true
MenuBarIconEnabled = false

["com.sempliva.Tiles".ActiveEdges]
ActiveEdgeBottom = "centerThird"
ActiveEdgeLeft = "halfLeft"
ActiveEdgeLowerLeft = "quarterBottomLeft"
ActiveEdgeLowerRight = "quarterBottomRight"
ActiveEdgeRight = "halfRight"
ActiveEdgeTop = "fullscreen"
ActiveEdgeUpperLeft = "quarterTopLeft"
ActiveEdgeUpperRight = "quarterTopRight"

["com.lwouis.alt-tab-macos"]
menubarIcon = 3
SUAutomaticallyUpdate = true
SUEnableAutomaticChecks = true

["com.microsoft.onenote.mac".NSUserKeyEquivalents]
"Heading 1" = "@^1"
"Heading 2" = "@^2"
"Heading 3" = "@^3"
"Heading 4" = "@^4"
"Heading 5" = "@^5"
"Heading 6" = "@^6"

["net.freemacsoft.appcleaner"]
ProtectDefaultApps = false
ProtectOpenedApps = false
SUEnableAutomaticChecks = true

["com.pilotmoon.scroll-reverser"]
HideIcon = true
InvertScrollingOn = true
ReverseTrackpad = false
StartAtLogin = true
