# /usr/libexec/PlistBuddy
# https://github.com/karmi/dotfiles/blob/master/mac/__application_preferences.sh
# https://macos-defaults.com/

["NSGlobalDomain"]
# To Mr. I'm too lazy to finish toml-to-defaults and instead type each property manually: defaults write -g AppleICUDateFormatStrings '{ 1 = "y-MM-dd";}'
AppleICUDateFormatStrings = { 1 = "y-MM-dd" }
AppleICUForce24HourTime = true
AppleInterfaceStyle = "Dark"
AppleKeyboardUIMode = 2                         # Move focus with Tab/Shift-Tab
AppleMenuBarVisibleInFullscreen = true
ApplePressAndHoldEnabled = false                # Repeat a key when held down, instead of showing accents
AppleScrollerPagingBehavior = true              # Jump to spot clicked in scroll bar
AppleShowAllExtensions = true
"com.apple.mouse.linear" = true                 # finally, a bearable macOS mouse experience
"com.apple.mouse.scaling" = 2.5                 # What if the cursor wasn't slower than the Mac Pro refresh cycle?
NSAutomaticCapitalizationEnabled = false
NSAutomaticPeriodSubstitutionEnabled = false    # No more double space for period
NSAutomaticQuoteSubstitutionEnabled = false
NSAutomaticSpellingCorrectionEnabled = false
NSNavPanelExpandedStateForSaveMode = true       # Expand save dialog by default
PMPrintingExpandedStateForPrint = true          # Expand print dialog by default

["com.apple.AppStore"]
InAppReviewEnabled = false

["/Library/Preferences/com.apple.commerce"] # needs sudo
AutoUpdate = true

# .DS_Store cringe
["com.apple.desktopservices"]
DSDontWriteNetworkStores = true
DSDontWriteUSBStores = true

["com.apple.dock"] # killall Dock
enable-spring-load-actions-on-all-items = true # Drag file over Dock item to open the app
expose-group-apps = false
mineffect = "suck"
minimize-to-application = true
mru-spaces = false      # Don't rearrange Spaces based on use
showAppExposeGestureEnabled = true
show-recents = false
wvous-bl-corner = 11    # Launchpad
wvous-br-corner = 4     # Show Desktop
wvous-tr-corner = 12    # Notification Center
# static-only = true # only show open apps

["com.apple.finder"] # killall Finder
AppleShowAllFiles = true
_FXSortFoldersFirst = true
FXArrangeGroupViewBy = "Name"
FXDefaultSearchScope = "SCcf" # Default search scope to current folder
FXEnableExtensionChangeWarning = false
FXPreferredViewStyle = "Nlsv" # Prefer list view
NSDocumentSaveNewDocumentsToCloud = false
ShowPathbar = true # Show breadcrumbs at the bottom

# macOS is a bad operating system
ComputerViewSettings.CustomViewStyleVersion.ExtendedListViewSettingsV2.calculateAllSizes = true
ComputerViewSettings.CustomViewStyleVersion.ListViewSettings.calculateAllSizes = true
FK_DefaultListViewSettings.calculateAllSizes = true
FK_StandardViewSettings.ExtendedListViewSettingsV2.calculateAllSizes = true
FK_StandardViewSettings.ListViewSettings.calculateAllSizes = true
PackageViewSettings.ExtendedListViewSettingsV2.calculateAllSizes = true
PackageViewSettings.ListViewSettings.calculateAllSizes = true
SearchViewSettings.ExtendedListViewSettingsV2.calculateAllSizes = true
SearchViewSettings.ListViewSettings.calculateAllSizes = true
StandardViewSettings.ExtendedListViewSettingsV2.calculateAllSizes = true
StandardViewSettings.ListViewSettings.calculateAllSizes = true
TrashViewSettings.ExtendedListViewSettingsV2.calculateAllSizes = true
TrashViewSettings.ListViewSettings.calculateAllSizes = true

["com.apple.menuextra.clock"] # killall SystemUIServer
DateFormat = "\"EEE d MMM H:mm\""
FlashDateSeparators = true

["com.apple.Safari"]
ShowFullURLInSmartSearchField = true

["com.apple.screensaver"]
askForPassword = true # Ask for password after sleep/screen saver

["/Library/Preferences/com.apple.SoftwareUpdate"]
AutomaticCheckEnabled = true
AutomaticDownload = true
AutomaticallyInstallMacOSUpdates = true
ConfigDataInstall = true
CriticalUpdateInstall = true

["com.100hps.captin"]
auto_launch = true
show_dock_icon = false
show_menu_bar_icon = false
show_on_launch = false
SUAutomaticallyUpdate = true

["com.lwouis.alt-tab-macos"]
alignThumbnails = true
fadeOutAnimation = true
hideColoredCircles = true
hideSpaceNumberLabels = true
hideWindowlessApps = true
holdShortcut = "\\\\U2318" # Replace jank macOS command-tab entirely
menubarIcon = 3
mouseHoverEnabled = false
spacesToShow = 1
SUAutomaticallyUpdate = true
SUEnableAutomaticChecks = true

["com.microsoft.onenote.mac".NSUserKeyEquivalents]
"Heading 1" = "@^1"
"Heading 2" = "@^2"
"Heading 3" = "@^3"
"Heading 4" = "@^4"
"Heading 5" = "@^5"
"Heading 6" = "@^6"

["com.microsoft.teams".NSUserKeyEquivalents]
"Quit Microsoft Teams" = "\\U200b" # Disable ⌘Q

["com.sempliva.Tiles"]
LaunchAtLoginEnabled = true
MenuBarIconEnabled = false

["com.sempliva.Tiles".ActiveEdges]
ActiveEdgeBottom = "centerThird"
ActiveEdgeLeft = "halfLeft"
ActiveEdgeLowerLeft = "quarterBottomLeft"
ActiveEdgeLowerRight = "quarterBottomRight"
ActiveEdgeRight = "halfRight"
ActiveEdgeTop = "fullscreen"
ActiveEdgeUpperLeft = "quarterTopLeft"
ActiveEdgeUpperRight = "quarterTopRight"

# defaults write com.spotify.client NSUserKeyEquivalents -dict-add "Go Back" "'@['"
["com.spotify.client".NSUserKeyEquivalents]
"Go Back" = "@["
"Go Forward" = "@]"

["com.pilotmoon.scroll-reverser"]
HideIcon = true
InvertScrollingOn = true
ReverseTrackpad = false
StartAtLogin = true

["net.freemacsoft.appcleaner"]
ProtectDefaultApps = false
ProtectOpenedApps = false
SUEnableAutomaticChecks = true

["org.p0deje.Maccy"]
hideTitle = true
removeFormattingByDefault = true
showInStatusBar = false
SUEnableAutomaticChecks = true
