[base]
brew = [
    "appcleaner",
    "alt-tab",
    "captin",
    "curl",
    "homebrew/cask-fonts/font-caskaydia-cove-nerd-font", # for starship
    "git",
    "google-chrome",
    "hiddenbar",
    "iterm2",
    "keka",
    "kekaexternalhelper",
    "maccy",
    "mas",
    "microsoft-office",
    "node",
    "openssl",
    "python",
    "scroll-reverser",
    "spotify",
    "tiles",
    "tldr",
    "visual-studio-code",
]

[personal]
brew = [
    "1password",
    "eqmac",
    "logitech-g-hub",
    "notion",
    "telegram",
]

[mobile]
depends = [ "java" ]
brew = [
    "altstore",
    "android-platform-tools",
    "binutils", # for gobjdump
    "checkra1n",
    "db-browser-for-sqlite",
    "ifunbox",
    "jadx",
    "scrcpy",
    "wkhtmltopdf", # for MobSF
]
git = [
    "https://github.com/androguard/androguard.git@cd0f6a6", # androsim
]
npm = [
    "igf",
]

[java]
brew = [
    "intellij-idea-ce",
    "mvn",
    "oracle-jdk",
]

[work]
brew = [
    "bitwarden",
    "burp-suite-professional",
    "cyberduck",
    "ghidra",
    "go",
    "gobuster",
    "hex-fiend",
    "meetingbar",
    "microsoft-edge",
    "microsoft-teams",
    "podman",
    "sqlmap",
    "subfinder",
    "swaks",
    "telnet",
    "testssl",
    "theharvester",
    "wget",
    "wpscanteam/tap/wpscan",
    "zenmap",
]
git = [
    "https://github.com/silentsignal/rsa_sign2n.git",
    "https://github.com/jkmartndale/wappalyzer.git",
]
mas = [
    497799835,  # Xcode
    917514700,  # Countdowns
    1127253508, # Unzip One
    1497506650, # Yubico Authenticator
    1569600264, # Pandan
]
pip = [
    "extract-msg",
    "ghtopdep",
]
