[base]
brew = [
    "1password",
    "appcleaner",
    "alt-tab",
    "caffeine",
    "captin",
    "curl",
    "eqmac",
    "homebrew/cask-fonts/font-caskaydia-cove-nerd-font", # for starship
    "fig",
    "fish",
    "git",
    "google-chrome",
    "hiddenbar",
    "homebrew/cask-drivers/logitech-g-hub",
    "insomnia",
    "iterm2",
    "jadx",
    "jq",
    "karabiner-elements",
    "keka",
    "kekaexternalhelper",
    "maccy",
    "mas",
    "microsoft-office",
    "notion",
    "openssl",
    "python",
    "qpdf",
    "scroll-reverser",
    "starship",
    "spotify",
    "telegram",
    "tiles",
    "tldr",
    "visual-studio-code",
    "zoom",
]

[work]
brew = [
    "android-platform-tools",
    "altstore",
    "apktool",
    "binutils", # for gobjdump
    "bitwarden",
    "burp-suite-professional",
    "checkra1n",
    "cyberduck",
    "db-browser-for-sqlite",
    "ghidra",
    "go",
    "gobuster",
    "hex-fiend",
    "ifunbox",
    "intellij-idea-ce",
    "intune-company-portal",
    "macfuse",
    "meetingbar",
    "microsoft-edge",
    "microsoft-remote-desktop",
    "microsoft-teams",
    "mongodb-realm-studio",
    "mvn",
    "node",
    "openvpn-connect",
    "oracle-jdk",
    "podman",
    "scrcpy",
    "gromgit/fuse/sshfs-mac",
    "sqlmap",
    "subfinder",
    "swaks",
    "telnet",
    "testssl",
    "theharvester",
    "wget",
    "wpscanteam/tap/wpscan",
    "wkhtmltopdf", # for MobSF
    "zenmap",
]
git = [
    "https://github.com/androguard/androguard.git@cd0f6a6", # androsim
    "https://github.com/silentsignal/rsa_sign2n.git",
    "https://github.com/AliasIO/wappalyzer.git",
]
mas = [
    497799835,  # Xcode
    917514700,  # Countdowns
    1127253508, # Unzip One
    1497506650, # Yubico Authenticator
    1569600264, # Pandan
]
npm = [
    "igf",
    "vercel",
]
pip = [
    "frida-tools",
    "ghtopdep",
    "objection",
    "pipdeptree",
]

[rust]
cargo = [
    "cargo-expand",
    "cargo-update",
    "sccache",
]
