[base]
brew = [
    "1password",
    "appcleaner",
    "alt-tab",
    "caffeine",
    "captin",
    "curl",
    "eqmac",
    "homebrew/cask-fonts/font-caskaydia-cove-nerd-font", # for starship
    "fish",
    "git",
    "google-chrome",
    "hiddenbar",
    "homebrew/cask-drivers/logitech-g-hub",
    "insomnia",
    "iterm2",
    "keka",
    "kekaexternalhelper",
    "maccy",
    "mas",
    "microsoft-office",
    "notion",
    "python",
    "scroll-reverser",
    "starship",
    "spotify",
    "telegram",
    "tiles",
    "time-out",
    "visual-studio-code",
    "zoom",
]

[work]
brew = [
    "android-platform-tools",
    "altstore",
    "burp-suite-professional",
    "checkra1n",
    "db-browser-for-sqlite",
    "ghidra",
    "gobuster",
    "hex-fiend",
    "ideviceinstaller",
    "intellij-idea-ce",
    "keepassxc",
    "macfuse",
    "meetingbar",
    "microsoft-edge",
    "microsoft-remote-desktop",
    "microsoft-teams",
    "mongodb-realm-studio",
    "mvn",
    "node",
    "openvpn-connect",
    "oracle-jdk",
    "podman",
    "scrcpy",
    "gromgit/fuse/sshfs-mac",
    "subfinder",
    "testssl",
    "theharvester",
    "wget",
    "wkhtmltopdf", # for MobSF
    "zenmap",
]
mas = [
    497799835,  # Xcode
    1127253508, # Unarchiver One
    1497506650, # Yubico Authenticator
]
npm = [
    "igf",
]
pip = [
    "frida-tools",
    "objection",
]
